### ISSUE TITLE
solc error: TypeError: solc.compileStandardWrapper is not a function

### ISSUE THREAD

**Issue by 0xbhushan777** [ac12644/NFT-Marketplace#1]
When i save the NFTMarketplace,sol smart contract it throws the following error

`[Error - 12:19:36 am] solc error: TypeError: solc.compileStandardWrapper is not a function
[Error - 12:19:36 am] solc error: TypeError: solc.compileStandardWrapper is not a function
    at compilationErrors (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\out\src\server.js:92:29)
    at validate (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\out\src\server.js:208:26)
    at c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\out\src\server.js:238:5
    at CallbackList.invoke (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-jsonrpc\lib\events.js:71:39)
    at Emitter.fire (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-jsonrpc\lib\events.js:135:36)
    at c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-languageserver\lib\main.js:213:33
    at handleNotification (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-jsonrpc\lib\main.js:476:43)
    at processMessageQueue (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-jsonrpc\lib\main.js:248:17)
    at Immediate._onImmediate (c:\Users\karap\.vscode\extensions\beaugunderson.solidity-extended-3.0.2\node_modules\vscode-jsonrpc\lib\main.js:235:13)
    at processImmediate (node:internal/timers:464:21)
00:19:36.04 validating NFTMarketplace.sol, solc done in 0s`

Please Guide me through this...

**Comment by ac12644** [comment]
Hey, sorry I don't get you. can you tell me what are you trying to do?

**Comment by 0xbhushan777** [comment]
@ac12644 the issue is resolved there I changed the compiler version and it fixed everything, sorry for bothering
